// This file was created by MAXCONVS SPK Skin Exporter (Version 1.61) -- Tuesday, March 16, 1999  13:26:05 PM

	SIMPLESPRITEDEF
		SIMPLESPRITETAG  "CHAIN01_SPRITE"
		NUMFRAMES 1
		BMINFO "CHAIN01" "CHAIN01.BMP" 
	ENDSIMPLESPRITEDEF

